name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

env:
  GOFLAGS: -mod=readonly

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      # actions/checkout@v4
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

    - name: Set up Go 1.25.9
      # actions/setup-go@v5
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
      with:
        go-version: '1.25.9'
      id: go

    - name: Install pam-devel
      run: sudo apt-get -y install libpam-dev

    - name: Verify committed modules
      run: |
        go mod download
        go mod verify

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...

    - name: Run govulncheck
      run: go run golang.org/x/vuln/cmd/govulncheck@v1.3.0 ./...
