services:
  rdpgw:
    container_name: rdpgw
    hostname: rdpgw
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile
    ports:
      - "8443:8443"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - ./rdpgw.yaml:/opt/rdpgw/rdpgw.yaml:ro
      - ./data/dashboard:/var/lib/rdpgw/dashboard
